name: Daily Commit

on:
  schedule:
    - cron: '0 7 * * *' # every day at 7 AM UTC
  workflow_dispatch:    # allows manual trigger

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make a change
        run: |
          echo "Last update: $(date -u)" >> activity.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add activity.txt
          git commit -m "Daily commit" || echo "No changes to commit"
          git push
